### PR TITLE
add byzantinium opcodes

### PR DESCRIPTION
**Pull request by nevillegrech**

### CODE REVIEW

**Comment by 0xl3x1** [comment]
@nevillegrech Thanks for this!

@zyzek Thoughts? Is there any additional logic needed for REVERT - it should also be a basic block boundary, right?

I think `STATICCALL` also needs to be added to `callcodes` in `src/exporter.py` and `is_call()` in `src/opcodes.py`

**Comment by lexibrent** [comment]
I think `STATICCALL` also needs to be added to `callcodes` in `src/exporter.py` and `is_call()` in `src/opcodes.py`

**Comment by zyzek** [comment]
`REVERT` should basically be equivalent to `THROW` or `INVALID` as far as the decompiler is concerned. So, yeah, it should terminate its basic block. That means that `REVERT` should be added to the list inside `OpCode.halts`, here https://github.com/nevillegrech/vandal/blob/71eaefd378abdf09299996e7db5e565ec08065e4/src/opcodes.py#L114. Additionally it should be added to the `throws` mapping in `exporter.CFGDotExporter`.

You're right about `STATICCALL`. Though `callcodes` inside `exporter` should really just use `OpCode.is_call`, shouldn't it?

**Comment by 0xl3x1** [comment]
Yeah, it should. I'll push a commit to fix that.

**Comment by 0xl3x1** [comment]
OK, I think this should work, but I'd like to add a test case to make sure before we merge

**Comment by 0xl3x1** [comment]
I want to wait for #43 to be merged first, then I can add some nice test cases for the new opcodes.

**Review by 0xl3x1 — APPROVED** [review]

**Pull request merged**
