### PR TITLE
Setuptools project conversion

### PR DESCRIPTION
**Pull request by SamuelMarks**
Before this gets too stale, I should send you a PR.

These new approaches seem to work:

    python -m vandal.cli.disassemble -h
    python -m vandal.cli.decompile -h

Whereas the version I was going for still needs a little work to support nargs properly:

    python -m vandal -h

Want me to recreate these changes so it's ready to merge, or did you want to wait until that^ version is ready?

### CODE REVIEW

**Comment by 0xl3x1** [comment]
Thanks for your work on this! I think it would be nice to package the CLIs as command line scripts so that when the setuptools package is installed they are added to $PATH automatically and can be run directly without needing to do something like `python -m vandal.cli.*`

See http://python-packaging.readthedocs.io/en/latest/command-line-scripts.html

Is that something you could do?

**Comment by SamuelMarks** [comment]
Yeah of course I can do it like that. Just not sure if that's desirable.

Will take a look at the code again, and send you a quick PR [similar to current; but rebased] that has proper setuptools and all; then we can debate the dis/advantages of each approach in terms of binary executables.

Sound good?

[probably have a chance this weekend to do this]

**Comment by 0xl3x1** [comment]
That sounds great, thanks! :+1:

**Comment by 0xl3x1** [comment]
Closing due to inactivity

**Pull request closed without merging**
